In [6]:
# ### DOWNLOAD ICESAT-2 DATA
# PATHS = c(
# "boreal_agb_202302061675670992_2952.tif",
# "boreal_agb_202302061675670680_2867.tif",
# "boreal_agb_202302061675668761_2868.tif",
# "boreal_agb_202302061675664058_2788.tif",
# "boreal_agb_202302061675663480_1955.tif",
# "boreal_agb_202302061675663035_2787.tif",
# "boreal_agb_202302061675662882_2707.tif",
# "boreal_agb_202302061675662860_2708.tif",
# "boreal_agb_202302061675660448_2024.tif",
# "boreal_agb_202302061675659857_1954.tif",
# "boreal_agb_202302061675659541_2094.tif")

# ORNL_username <- 'nhunka'
# ORNL_password <- 'Boreal_tiles1'
# DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/"

# for (i in 1:length(PATHS)){
#     DOWNLOAD_LOCATION <- paste0(DOWNLOAD_FOLDER,basename(PATHS[i]))
#     if (!file.exists(DOWNLOAD_LOCATION)){
#         PATH_i = paste("wget --user",ORNL_username, "--password ",ORNL_password, paste0("https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/",basename(PATHS[i])), "-O", DOWNLOAD_LOCATION)
#         print(paste("Downloading...",DOWNLOAD_LOCATION))
#         print(PATH_i)
#         system(PATH_i)
# }
# }

[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670992_2952.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/boreal_agb_202302061675670992_2952.tif -O /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670992_2952.tif"
[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670680_2867.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/boreal_agb_202302061675670680_2867.tif -O /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670680_2867.tif"
[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675668761_2868.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://

In [5]:
import s3fs
import os

DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/"
list = ["s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/14/45/53/581150/boreal_agb_2020_202407171721252667_0002093.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/11/47/273906/boreal_agb_2020_202407171721254217_0002023.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/14/06/396535/boreal_agb_2020_202407171721254333_0002867.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/16/31/132315/boreal_agb_2020_202407171721254498_0002094.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/19/30/772176/boreal_agb_2020_202407171721254671_0002024.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/28/09/128143/boreal_agb_2020_202407171721255189_0001955.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/40/22/201905/boreal_agb_2020_202407171721255911_0002788.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/46/32/268143/boreal_agb_2020_202407171721256279_0002708.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/46/39/917014/boreal_agb_2020_202407171721256285_0002787.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/06/16/852593/boreal_agb_2020_202407171721257466_0002786.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/27/03/976744/boreal_agb_2020_202407171721258706_0002707.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/27/24/692311/boreal_agb_2020_202407171721258736_0001954.tif",
"s3://maap-ops-workspace/lduncanson/dps_outsput/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/58/01/627651/boreal_agb_2020_202407171721260574_0002952.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/17/20/58/787642/boreal_agb_2020_202407171721261957_0002166.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/17/36/29/821669/boreal_agb_2020_202407171721262874_0002868.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/10/45/985168/boreal_agb_2020_202407191721394557_0001953.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/17/08/177877/boreal_agb_2020_202407191721394947_0002092.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/45/51/231469/boreal_agb_2020_202407191721396662_0002022.tif"]

DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_heights/"
if not os.path.exists(DOWNLOAD_FOLDER): os.mkdir(DOWNLOAD_FOLDER)
list = ["s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/21/32/47/186886/boreal_ht_2020_202407251721968278_0002166.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/21/53/43/785836/boreal_ht_2020_202407251721969521_0002952.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/15/56/144922/boreal_ht_2020_202407251721970840_0002787.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/30/52/545185/boreal_ht_2020_202407251721971751_0002024.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/32/26/843565/boreal_ht_2020_202407251721971862_0002022.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/45/39/383067/boreal_ht_2020_202407251721972655_0001953.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/53/13/131734/boreal_ht_2020_202407251721973113_0002092.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/04/17/463310/boreal_ht_2020_202407251721973748_0002867.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/07/39/011539/boreal_ht_2020_202407251721973941_0002788.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/10/17/738194/boreal_ht_2020_202407251721974120_0001955.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/10/47/840882/boreal_ht_2020_202407251721974136_0002868.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/28/21/592890/boreal_ht_2020_202407251721975203_0002023.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/41/35/433171/boreal_ht_2020_202407251721976006_0002093.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/41/43/627070/boreal_ht_2020_202407251721976009_0001954.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/44/33/660368/boreal_ht_2020_202407251721976162_0002707.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/08/33/294345/boreal_ht_2020_202407261721977605_0002708.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/25/20/759122/boreal_ht_2020_202407261721978619_0002094.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/29/17/222050/boreal_ht_2020_202407261721978844_0002786.tif"]
s3 = s3fs.S3FileSystem(anon=False)
for file in list:
    s3.download(file, DOWNLOAD_FOLDER)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import numpy as np
from osgeo import gdal, osr

def array2raster(rasterfn,ORX,ORY,newRasterfn,array):
    raster = gdal.Open(str(rasterfn))
    geotransform = raster.GetGeoTransform() 
    originX = ORX
    originY = ORY
    pixelWidth = geotransform[1]
    pixelHeight = geotransform[5]
    cols = raster.RasterXSize
    rows = raster.RasterYSize

    driver = gdal.GetDriverByName('GTiff')
    outRaster = driver.Create(str(newRasterfn), cols, rows, 1, gdal.GDT_Float32,['COMPRESS=DEFLATE', 'TILED=YES','BIGTIFF=IF_NEEDED'])
    outRaster.SetGeoTransform((originX, pixelWidth, 0, originY, 0, pixelHeight))
    outband = outRaster.GetRasterBand(1)
    outband.WriteArray(array)
    outRasterSRS = osr.SpatialReference()
    outRasterSRS.ImportFromWkt(raster.GetProjectionRef())
    outRaster.SetProjection(outRasterSRS.ExportToWkt())
    outband.FlushCache()

In [ ]:
import rasterio
import os
import argparse
from rasterio.io import MemoryFile
from rasterio.rio import options
from rasterio.shutil import copy, delete
from rasterio.vrt import WarpedVRT
from rio_cogeo.cogeo import cog_translate
from rio_cogeo.profiles import cog_profiles
from rasterio.transform import from_origin
from rasterio.crs import CRS


FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID"

for dirName, subdirList, fileList in os.walk(FOLDER):
    for fname in fileList:
        if fname.endswith("_MON_L2A.csv"):
            OUTFILE = os.path.join(FOLDER,fname.split('.')[0] + '.tif')
            print(OUTFILE)
            if os.path.exists(OUTFILE): 
                os.remove(OUTFILE)
            L2A = pd.read_csv(os.path.join(FOLDER,fname))
            x = L2A["lon_lowestmode.x"]
            y = L2A["lat_lowestmode.x"]
            z = L2A.rh98
            n = 400 # n x n is the size of the output raster
            
            zi, yi, xi = np.histogram2d(y, x, bins=(n,n), weights=z)
            counts, _, _ = np.histogram2d(y, x, bins=(n,n))
            
            print("counts", counts)
            print("zi", zi)
            
            # zi = zi / counts
            zi = np.divide(zi, counts, out=np.zeros_like(zi), where=counts != 0)
            
            # zi = np.ma.masked_invalid(zi)
            # z[np.isnan(z)] = 0
            
            # fig, ax = plt.subplots()
            # ax.pcolormesh(xi, yi, zi) ## edgecolors='black'
            # scat = ax.scatter(x, y, c=z, s=0)
            # fig.colorbar(scat)
            # ax.margins(0.05)
            
            # plt.show()
            
            z = np.array(zi.data[::-1])
            # Set NaN values in 'z' to 0
            z[np.isnan(z)] = 0

            pixel_width = xi[1] - xi[0]
            pixel_height = yi[1] - yi[0]
            x_min = xi[0]# - pixel_width / 2
            y_max = yi[np.size(yi)-1]# + pixel_height / 2
            
            # Define the transform (geotransform equivalent in rasterio)
            transform = from_origin(x_min, y_max, pixel_width, pixel_height)
            print(x_min)
            print(y_max)
            
            # Define the CRS (coordinate reference system, EPSG:4326)
            crs = CRS.from_epsg(4326)
            
            kwargs = {
                'driver': 'GTiff',
                'dtype': z.dtype,
                'count': 1,  # Number of bands
                'height': z.shape[0],
                'width': z.shape[1],
                'crs': crs,
                'transform': transform,
                'predictor': 2
            }
            
            with MemoryFile() as memfile:
                with memfile.open(**kwargs) as mem:
                    # Populate the input file with numpy array
                    mem.write(z.reshape(1, z.shape[0], z.shape[1]))
            
                    dst_profile = cog_profiles.get("deflate")
                    cog_translate(
                        mem,
                        OUTFILE,
                        dst_profile,
                        in_memory=False
                    )
            
            print("GeoTIFF has been created successfully with GDAL.")

/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_11_MON_L2A.tif
counts [[ 2.  4. 10. ...  6.  6.  4.]
 [17.  9.  8. ...  8.  7. 14.]
 [ 8. 17. 15. ...  0.  0.  0.]
 ...
 [11. 12. 12. ...  3.  1.  8.]
 [ 3.  6.  4. ... 18. 19. 16.]
 [ 7.  5.  8. ...  4.  8. 10.]]
zi [[ 5.75999999 14.03000021 38.99999976 ... 15.02000022 15.9000001
  10.23000002]
 [71.90999985 49.60999942 38.2099998  ... 22.12000036 17.50999999
  36.32000017]
 [26.45000005 67.01000047 51.05999947 ...  0.          0.
   0.        ]
 ...
 [29.66000032 31.52999997 31.42999959 ... 11.27000022  3.96000004
  24.03999996]
 [ 7.54999995 15.21000028 10.12999988 ... 55.53999996 55.69999981
  52.49000001]
 [18.1400001  12.71000028 20.91000009 ... 38.10999894 25.83000016
  34.44999957]]
94.0373541424532
50.610949537773


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/74a26dee-de72-42b2-b7a3-6c314cdac828/74a26dee-de72-42b2-b7a3-6c314cdac828.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_11_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_12_MON_L2A.tif
counts [[10. 10. 12. ...  7.  7.  5.]
 [ 9.  6.  7. ...  3.  4.  4.]
 [ 2.  3.  2. ...  2.  1.  0.]
 ...
 [ 0.  2.  0. ...  1.  8. 13.]
 [ 3.  8.  6. ...  2.  0.  0.]
 [ 9.  5.  0. ...  1.  2.  1.]]
zi [[25.8099997  25.61999965 33.25999975 ... 17.99000001 17.15000033
  12.45000005]
 [23.19000006 16.11999989 21.27999997 ...  7.50999999 10.00999999
   9.94000006]
 [ 5.6099999   7.9599998   5.26999998 ...  4.9000001   2.47000003
   0.        ]
 ...
 [ 0.          9.18999982  0.         ...  3.92000008 33.13999987
  46.07000017]
 [15.19000006 40.25       38.87999964 ... 11.40999985  0.
   0.        ]
 [32.50000024 22.12999988  0.         ...  8.73999977 15.5
   5.03000021]]
92.0373547148086
49.6109499457992


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/5b663213-bf0b-4636-b559-8ae8eafeb0b8/5b663213-bf0b-4636-b559-8ae8eafeb0b8.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_12_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_13_MON_L2A.tif


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/e77eab7c-e03d-40ee-b043-8e7f87c7735b/e77eab7c-e03d-40ee-b043-8e7f87c7735b.tif' mode='w+'>



counts [[ 2.  1.  1. ...  4.  1.  3.]
 [ 5.  4.  7. ... 15. 17. 13.]
 [ 0.  4.  3. ...  9.  8.  4.]
 ...
 [ 0.  0.  0. ... 12. 12. 12.]
 [ 0.  0.  0. ...  5.  3.  2.]
 [ 0.  0.  0. ... 10.  7.  5.]]
zi [[10.00999975  6.07999992  4.65999985 ... 18.47999954  5.17999983
  16.16000009]
 [31.69000053 24.75       39.00000072 ... 79.32000065 94.04000044
  80.88999987]
 [ 0.         16.77999997 28.95000076 ... 46.72000027 40.93000007
  21.86999989]
 ...
 [ 0.          0.          0.         ... 30.38999987 31.1099999
  31.27000046]
 [ 0.          0.          0.         ... 13.81999993  7.58000016
   5.11999989]
 [ 0.          0.          0.         ... 24.86000061 17.75
  12.86000037]]
93.037354326909
50.6109499643647


Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_13_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_14_MON_L2A.tif
counts [[ 5.  7.  7. ...  1.  4.  3.]
 [ 0.  4.  3. ... 10. 10. 11.]
 [11.  6.  3. ...  3.  3.  4.]
 ...
 [13. 22. 25. ...  7.  7.  3.]
 [20. 15.  8. ...  1.  1.  1.]
 [12.  9.  3. ... 10. 11.  8.]]
zi [[36.92999983 43.76000023 29.21000028 ...  3.54999995 13.31000018
   9.00999999]
 [ 0.         24.68000031 13.62000036 ... 42.68999982 44.63000059
  30.44000006]
 [58.32999969 28.93999958 11.17999983 ...  8.55999994 10.47000003
  16.46000004]
 ...
 [45.94999957 68.32999992 91.33000016 ... 39.91000032 37.73000026
  16.57000017]
 [88.01999927 45.28000045 26.58000016 ...  5.75        4.28999996
   3.47000003]
 [63.40999961 29.16999984 15.00000048 ... 53.68999982 46.38999987
  37.67000008]]
91.0373562296455
49.610949854879


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/9a38bd8b-5fad-43c5-aaab-9352ccb16fbd/9a38bd8b-5fad-43c5-aaab-9352ccb16fbd.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_14_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_15_MON_L2A.tif
counts [[ 2.  3.  4. ...  5.  7.  4.]
 [ 7.  5.  6. ...  0.  0.  3.]
 [ 6.  2.  3. ...  2.  3.  2.]
 ...
 [17. 16. 17. ...  0.  0.  0.]
 [17. 17. 14. ...  0.  0.  0.]
 [26. 17. 21. ...  0.  0.  0.]]
zi [[12.53999996 42.45999908 27.47000027 ... 42.32999992 46.48999977
  27.31999969]
 [46.17000008 25.8099997  30.34999943 ...  0.          0.
  28.24999952]
 [26.92000008 10.78999996  9.30000019 ... 14.45000029 16.11000013
  10.17000008]
 ...
 [54.61000013 48.64000034 47.39999986 ...  0.          0.
   0.        ]
 [72.63999987 51.98999953 36.5        ...  0.          0.
   0.        ]
 [75.43999982 47.41000032 65.23000026 ...  0.          0.
   0.        ]]
92.0373540795052
50.6109486977635


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/5f89ea62-d9b9-458c-86ea-804d092312e2/5f89ea62-d9b9-458c-86ea-804d092312e2.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_15_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_16_MON_L2A.tif
counts [[20. 28. 36. ...  3.  2.  1.]
 [13.  9.  2. ...  6.  7.  9.]
 [15. 10. 15. ...  6.  8.  6.]
 ...
 [ 4.  3.  1. ... 13. 17. 13.]
 [ 0.  0.  0. ... 20. 12. 14.]
 [ 5.  3.  4. ... 13. 15. 21.]]
zi [[ 85.71999979  91.45000148 133.46000004 ...  23.42000055  15.22000027
    8.84000015]
 [ 59.84000039  36.02000046   7.62999988 ...  56.54000044  48.73000026
   69.4900012 ]
 [ 95.78000069  46.36000109  55.77000046 ...  34.57999992  41.75999928
   25.45000052]
 ...
 [ 32.54000044  29.43999958  13.56999969 ...  54.25        49.71000004
   40.64999986]
 [  0.           0.           0.         ...  59.1099999   32.62000036
   40.71999955]
 [ 52.34999943  19.74000025  56.07999992 ...  43.86999965  44.52999973
   58.40999985]]
91.0373570906393
50.6109497731506


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/a7d662c0-226d-4aa2-96ed-2a76865031f1/a7d662c0-226d-4aa2-96ed-2a76865031f1.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_16_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_17_MON_L2A.tif
counts [[11.  9.  6. ... 11. 15. 10.]
 [ 4.  8.  5. ...  2.  2.  0.]
 [ 1.  4.  5. ...  2.  2.  2.]
 ...
 [ 0.  0.  0. ...  2.  2.  3.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]]
zi [[75.72000003 61.30000019 36.63000011 ... 30.78000069 41.93000007
  26.11000013]
 [29.86999989 65.52000046 25.17999983 ... 15.57000041  5.46000004
   0.        ]
 [ 5.03999996 20.51999974 34.55999947 ... 25.61999917 14.75999975
   5.93000007]
 ...
 [ 0.          0.          0.         ... 41.60000038 30.18000031
  81.64999962]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.         67.31999969 ...  0.          0.
   0.        ]]
108.037355776952
49.6109494515788


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/c28af9be-7d19-4d45-be14-3e034144580f/c28af9be-7d19-4d45-be14-3e034144580f.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_17_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_18_MON_L2A.tif
counts [[ 6.  5. 10. ...  0.  5.  7.]
 [11. 10.  5. ...  7.  1.  0.]
 [ 4.  5.  7. ...  0.  0.  0.]
 ...
 [ 2.  7. 12. ...  2.  0.  0.]
 [ 5.  2.  0. ...  0.  0.  0.]
 [ 6.  8.  7. ...  1.  0.  0.]]
zi [[ 33.65000057  43.60999918 101.23000145 ...   0.          45.77999973
   44.36999989]
 [ 79.98000169  53.2300005   30.54999971 ... 152.48999929  19.05999947
    0.        ]
 [ 13.30000019  16.99000001  31.03999949 ...   0.           0.
    0.        ]
 ...
 [ 15.92999983  98.35999942  88.89000082 ...  58.28999901   0.
    0.        ]
 [ 35.97000027  12.32000017   0.         ...   0.           0.
    0.        ]
 [ 43.09000015  58.75999975  58.79999876 ...  22.45000076   0.
    0.        ]]
107.037357108785
49.6109444087761


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/dc6ebeb4-05bf-47bb-802c-72648fccd78a/dc6ebeb4-05bf-47bb-802c-72648fccd78a.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_18_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_19_MON_L2A.tif
counts [[ 4.  1.  0. ...  5.  8.  7.]
 [ 0.  0.  3. ... 10. 16. 13.]
 [ 7.  8.  6. ... 11.  6.  5.]
 ...
 [25. 21. 10. ...  0.  0.  0.]
 [ 2.  5. 22. ...  9. 10.  8.]
 [20. 15. 15. ...  0.  1.  6.]]
zi [[10.61999989  2.5         0.         ... 35.77000022 48.72000003
  33.11999989]
 [ 0.          0.          7.80000019 ... 58.33000088 76.25000072
  47.11000037]
 [22.85000014 21.13000011 17.27999997 ... 58.94999981 34.24000072
  26.36999989]
 ...
 [71.17000031 62.42999935 30.58000016 ...  0.          0.
   0.        ]
 [ 5.08000016 13.55999994 59.19000006 ... 98.93999863 60.63999939
  87.76000071]
 [57.63000011 44.87999964 39.8099997  ...  0.         16.01000023
  50.75000048]]
106.037354998044
49.6109496203229


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/b3b6c779-9781-4d79-be2a-dcd503126a98/b3b6c779-9781-4d79-be2a-dcd503126a98.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_19_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_1_MON_L2A.tif
counts [[3. 3. 3. ... 4. 1. 0.]
 [4. 5. 3. ... 0. 0. 2.]
 [0. 0. 0. ... 1. 1. 0.]
 ...
 [3. 3. 4. ... 3. 3. 4.]
 [1. 1. 1. ... 3. 4. 3.]
 [0. 0. 0. ... 1. 3. 2.]]
zi [[ 39.81000042  10.05000019  10.35000014 ... 247.71000099  96.19000244
    0.        ]
 [ 25.55999994  27.01000023   8.41000009 ...   0.           0.
   26.92000008]
 [  0.           0.           0.         ...  14.92000008  20.31999969
    0.        ]
 ...
 [ 14.92000008  11.13999987  26.23000002 ...  78.07999992  77.43999863
   86.5899992 ]
 [  4.67000008   3.70000005   2.83999991 ...  93.43999863 106.01999855
   51.30000019]
 [  0.           0.           0.         ...  13.44999981  39.53999996
   22.84000015]]
107.037355060962
50.6109488512985


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/bb7496f0-6b5e-49a2-a516-10f806604555/bb7496f0-6b5e-49a2-a516-10f806604555.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_1_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_2_MON_L2A.tif
counts [[15.  5.  1. ...  3.  2.  3.]
 [ 7. 19. 26. ...  7.  5.  6.]
 [10.  8.  4. ...  4.  8.  3.]
 ...
 [ 6.  6.  6. ...  5. 14. 27.]
 [18. 21. 11. ...  9. 12. 11.]
 [ 1.  1.  6. ... 18. 20. 16.]]
zi [[ 40.83000064  14.0999999    2.88000011 ...   8.47999978   5.99000001
    9.52999973]
 [ 18.45000005  51.46000004  69.78000021 ...  23.23000026  13.23000002
   15.47999978]
 [ 28.79999971  21.51000023   9.53000021 ...  11.52999997  23.59000015
    9.44999981]
 ...
 [ 15.05999994  15.83999991  14.92000008 ...  53.97999954 142.32999992
  350.50999928]
 [ 48.35000038  57.20999932  29.85000014 ...  64.46000004  74.4199996
   70.66999984]
 [  2.6500001    3.20000005  16.71000004 ... 200.20999932 194.07999945
  161.5400002 ]]
95.0373540932508
49.6109497403471


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/5e796fae-3f96-46ee-be91-0c865a9a3673/5e796fae-3f96-46ee-be91-0c865a9a3673.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_2_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_3_MON_L2A.tif
counts [[10. 10.  9. ... 12. 18. 14.]
 [ 7.  4.  4. ...  6.  6.  8.]
 [ 0.  2.  8. ... 17. 14. 14.]
 ...
 [ 2. 14. 16. ... 17.  5.  4.]
 [16. 11. 11. ... 10. 23. 16.]
 [15. 18. 15. ...  4.  3.  4.]]
zi [[25.23000026 25.57999992 24.30999994 ... 31.66999984 54.94000006
  41.12000036]
 [17.00999975  9.58999968  9.37999988 ... 15.32000017 16.62999988
  22.5599997 ]
 [ 0.          4.97000003 19.56999993 ... 47.16999984 40.31000042
  39.27999997]
 ...
 [ 5.91000009 45.64999938 66.28999996 ... 46.67999935 13.56000018
  10.38000011]
 [50.07999992 30.01999998 30.54999948 ... 26.78999972 62.70000005
  43.42999983]
 [57.26999998 70.31000018 69.85999942 ... 12.91000009  8.31999993
  12.08999991]]
94.0373562867492
49.6109497996439


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/7c38ebdc-c54f-42bb-adac-19255b8bbd50/7c38ebdc-c54f-42bb-adac-19255b8bbd50.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_3_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_4_MON_L2A.tif
counts [[13.  5.  6. ...  3. 10.  9.]
 [ 9. 14. 10. ... 17.  8.  6.]
 [ 3.  2.  3. ...  4. 12. 11.]
 ...
 [10. 14. 13. ... 16.  9. 10.]
 [10. 10. 10. ...  6.  9. 12.]
 [15. 16. 13. ... 15. 13.  8.]]
zi [[ 39.05000019  12.75999999  17.24000025 ...  33.39000034  96.53999996
  101.49000072]
 [ 26.3499999   39.88000035  73.82999897 ... 156.40999985  69.13999987
   62.49000025]
 [  8.41000009  10.63999987  11.41000032 ...  20.08999991 122.9800024
   86.37999988]
 ...
 [ 30.71000004  55.74000001  85.87000012 ... 321.48999929  58.64999962
  101.68000054]
 [ 37.38000059  38.18999934  39.91000032 ... 108.2200017   80.20000029
  126.64999866]
 [ 53.69999957  54.47000027  64.15999985 ... 178.0600009  150.90999937
   74.15000057]]
95.0373549772785
50.6109473289798


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/6d1d182e-3eea-47ef-b8e5-fa02419d4e0e/6d1d182e-3eea-47ef-b8e5-fa02419d4e0e.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_4_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_5_MON_L2A.tif
counts [[ 6. 10.  9. ...  2.  4.  3.]
 [ 5.  6.  9. ...  2.  1.  3.]
 [11.  4.  1. ...  3.  6.  7.]
 ...
 [ 0.  0.  2. ... 18. 22. 20.]
 [ 0.  2.  6. ...  9.  4.  4.]
 [ 3.  4.  4. ...  9. 11.  9.]]
zi [[ 17.41000009  34.78000021  28.28999996 ...   6.75999999  14.0999999
    8.86000013]
 [ 16.56999969  21.1500001   28.12999988 ...   6.50999999   3.66000009
    8.5999999 ]
 [ 40.3900001   14.17000031   3.0999999  ...   9.00999999  19.00999999
   24.29999995]
 ...
 [  0.           0.          66.68000031 ...  50.0999999   57.45000005
   54.17999983]
 [  0.          22.20000052 101.94000053 ...  28.89000034  12.31999993
   12.48000002]
 [ 13.55999994  17.57000017  34.63999987 ...  26.05000019  33.44000006
   26.10000014]]
105.037354891895
49.6109496421254


/tmp/ipykernel_2631/2305939387.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/d8d94607-7fb2-4df1-904d-5d9e49ff7ceb/d8d94607-7fb2-4df1-904d-5d9e49ff7ceb.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_5_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_6_MON_L2A.tif


In [23]:
# open raster and choose band to find min, max
raster = '/projects/output_gdal_200_8.tif'
#gtif = gdal.Open(raster)
#srcband = gtif.GetRasterBand(1)

with rasterio.open(raster) as dataset:
    data = dataset.read()

    if dataset.nodata is not None:
        data = np.ma.masked_equal(data, dataset.nodata)

    # Compute statistics
    min_value = np.min(data)
    max_value = np.max(data)
    mean_value = np.mean(data)
    std_dev = np.std(data)

    # Print the statistics
    print(f"Min: {min_value}")
    print(f"Max: {max_value}")
    print(f"Mean: {mean_value}")
    print(f"Standard Deviation: {std_dev}")

Min: 0
Max: 80
Mean: 13.53555
Standard Deviation: 8.726241241078544
