In [6]:
# ### DOWNLOAD ICESAT-2 DATA
# PATHS = c(
# "boreal_agb_202302061675670992_2952.tif",
# "boreal_agb_202302061675670680_2867.tif",
# "boreal_agb_202302061675668761_2868.tif",
# "boreal_agb_202302061675664058_2788.tif",
# "boreal_agb_202302061675663480_1955.tif",
# "boreal_agb_202302061675663035_2787.tif",
# "boreal_agb_202302061675662882_2707.tif",
# "boreal_agb_202302061675662860_2708.tif",
# "boreal_agb_202302061675660448_2024.tif",
# "boreal_agb_202302061675659857_1954.tif",
# "boreal_agb_202302061675659541_2094.tif")

# ORNL_username <- 'nhunka'
# ORNL_password <- 'Boreal_tiles1'
# DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/"

# for (i in 1:length(PATHS)){
#     DOWNLOAD_LOCATION <- paste0(DOWNLOAD_FOLDER,basename(PATHS[i]))
#     if (!file.exists(DOWNLOAD_LOCATION)){
#         PATH_i = paste("wget --user",ORNL_username, "--password ",ORNL_password, paste0("https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/",basename(PATHS[i])), "-O", DOWNLOAD_LOCATION)
#         print(paste("Downloading...",DOWNLOAD_LOCATION))
#         print(PATH_i)
#         system(PATH_i)
# }
# }

[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670992_2952.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/boreal_agb_202302061675670992_2952.tif -O /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670992_2952.tif"
[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670680_2867.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://daac.ornl.gov/daacdata/above/Boreal_AGB_Density_ICESat2/data/boreal_agb_202302061675670680_2867.tif -O /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675670680_2867.tif"
[1] "Downloading... /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/boreal_agb_202302061675668761_2868.tif"
[1] "wget --user nhunka --password  Boreal_tiles1 https://

In [5]:
import s3fs
import os

DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_files/"
list = ["s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/14/45/53/581150/boreal_agb_2020_202407171721252667_0002093.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/11/47/273906/boreal_agb_2020_202407171721254217_0002023.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/14/06/396535/boreal_agb_2020_202407171721254333_0002867.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/16/31/132315/boreal_agb_2020_202407171721254498_0002094.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/19/30/772176/boreal_agb_2020_202407171721254671_0002024.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/28/09/128143/boreal_agb_2020_202407171721255189_0001955.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/40/22/201905/boreal_agb_2020_202407171721255911_0002788.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/46/32/268143/boreal_agb_2020_202407171721256279_0002708.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/15/46/39/917014/boreal_agb_2020_202407171721256285_0002787.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/06/16/852593/boreal_agb_2020_202407171721257466_0002786.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/27/03/976744/boreal_agb_2020_202407171721258706_0002707.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/27/24/692311/boreal_agb_2020_202407171721258736_0001954.tif",
"s3://maap-ops-workspace/lduncanson/dps_outsput/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/16/58/01/627651/boreal_agb_2020_202407171721260574_0002952.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/17/20/58/787642/boreal_agb_2020_202407171721261957_0002166.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/17/17/36/29/821669/boreal_agb_2020_202407171721262874_0002868.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/10/45/985168/boreal_agb_2020_202407191721394557_0001953.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/17/08/177877/boreal_agb_2020_202407191721394947_0002092.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/AGB_H30_2020/Version2_SD/2024/07/19/06/45/51/231469/boreal_agb_2020_202407191721396662_0002022.tif"]

DOWNLOAD_FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/MNG/BOREAL_heights/"
if not os.path.exists(DOWNLOAD_FOLDER): os.mkdir(DOWNLOAD_FOLDER)
list = ["s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/21/32/47/186886/boreal_ht_2020_202407251721968278_0002166.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/21/53/43/785836/boreal_ht_2020_202407251721969521_0002952.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/15/56/144922/boreal_ht_2020_202407251721970840_0002787.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/30/52/545185/boreal_ht_2020_202407251721971751_0002024.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/32/26/843565/boreal_ht_2020_202407251721971862_0002022.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/45/39/383067/boreal_ht_2020_202407251721972655_0001953.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/22/53/13/131734/boreal_ht_2020_202407251721973113_0002092.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/04/17/463310/boreal_ht_2020_202407251721973748_0002867.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/07/39/011539/boreal_ht_2020_202407251721973941_0002788.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/10/17/738194/boreal_ht_2020_202407251721974120_0001955.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/10/47/840882/boreal_ht_2020_202407251721974136_0002868.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/28/21/592890/boreal_ht_2020_202407251721975203_0002023.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/41/35/433171/boreal_ht_2020_202407251721976006_0002093.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/41/43/627070/boreal_ht_2020_202407251721976009_0001954.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/25/23/44/33/660368/boreal_ht_2020_202407251721976162_0002707.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/08/33/294345/boreal_ht_2020_202407261721977605_0002708.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/25/20/759122/boreal_ht_2020_202407261721978619_0002094.tif",
"s3://maap-ops-workspace/lduncanson/dps_output/run_boreal_biomass_map/boreal_agb_2024_v6/Ht_H30_2020/Version2_SD/2024/07/26/00/29/17/222050/boreal_ht_2020_202407261721978844_0002786.tif"]
s3 = s3fs.S3FileSystem(anon=False)
for file in list:
    s3.download(file, DOWNLOAD_FOLDER)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import numpy as np
from osgeo import gdal, osr

def array2raster(rasterfn,ORX,ORY,newRasterfn,array):
    raster = gdal.Open(str(rasterfn))
    geotransform = raster.GetGeoTransform() 
    originX = ORX
    originY = ORY
    pixelWidth = geotransform[1]
    pixelHeight = geotransform[5]
    cols = raster.RasterXSize
    rows = raster.RasterYSize

    driver = gdal.GetDriverByName('GTiff')
    outRaster = driver.Create(str(newRasterfn), cols, rows, 1, gdal.GDT_Float32,['COMPRESS=DEFLATE', 'TILED=YES','BIGTIFF=IF_NEEDED'])
    outRaster.SetGeoTransform((originX, pixelWidth, 0, originY, 0, pixelHeight))
    outband = outRaster.GetRasterBand(1)
    outband.WriteArray(array)
    outRasterSRS = osr.SpatialReference()
    outRasterSRS.ImportFromWkt(raster.GetProjectionRef())
    outRaster.SetProjection(outRasterSRS.ExportToWkt())
    outband.FlushCache()

In [7]:
import rasterio
import os
import argparse
from rasterio.io import MemoryFile
from rasterio.rio import options
from rasterio.shutil import copy, delete
from rasterio.vrt import WarpedVRT
from rio_cogeo.cogeo import cog_translate
from rio_cogeo.profiles import cog_profiles
from rasterio.transform import from_origin
from rasterio.crs import CRS


FOLDER = "/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID"

for dirName, subdirList, fileList in os.walk(FOLDER):
    for fname in fileList:
        if fname.endswith("_MON_L2A.csv"):
            OUTFILE = os.path.join(FOLDER,fname.split('.')[0] + '.tif')
            print(OUTFILE)
            if os.path.exists(OUTFILE): 
                os.remove(OUTFILE)
            L2A = pd.read_csv(os.path.join(FOLDER,fname))
            x = L2A["lon_lowestmode.x"]
            y = L2A["lat_lowestmode.x"]
            z = L2A.rh98
            n = 200 # n x n is the size of the output raster
            
            zi, yi, xi = np.histogram2d(y, x, bins=(n,n), weights=z)
            counts, _, _ = np.histogram2d(y, x, bins=(n,n))
            
            print("counts", counts)
            print("zi", zi)
            
            # zi = zi / counts
            zi = np.divide(zi, counts, out=np.zeros_like(zi), where=counts != 0)
            
            # zi = np.ma.masked_invalid(zi)
            # z[np.isnan(z)] = 0
            
            # fig, ax = plt.subplots()
            # ax.pcolormesh(xi, yi, zi) ## edgecolors='black'
            # scat = ax.scatter(x, y, c=z, s=0)
            # fig.colorbar(scat)
            # ax.margins(0.05)
            
            # plt.show()
            
            z = np.array(zi.data[::-1])
            # Set NaN values in 'z' to 0
            z[np.isnan(z)] = 0

            pixel_width = xi[1] - xi[0]
            pixel_height = yi[1] - yi[0]
            x_min = xi[0]# - pixel_width / 2
            y_max = yi[np.size(yi)-1]# + pixel_height / 2
            
            # Define the transform (geotransform equivalent in rasterio)
            transform = from_origin(x_min, y_max, pixel_width, pixel_height)
            print(x_min)
            print(y_max)
            
            # Define the CRS (coordinate reference system, EPSG:4326)
            crs = CRS.from_epsg(4326)
            
            kwargs = {
                'driver': 'GTiff',
                'dtype': z.dtype,
                'count': 1,  # Number of bands
                'height': z.shape[0],
                'width': z.shape[1],
                'crs': crs,
                'transform': transform,
                'predictor': 2
            }
            
            with MemoryFile() as memfile:
                with memfile.open(**kwargs) as mem:
                    # Populate the input file with numpy array
                    mem.write(z.reshape(1, z.shape[0], z.shape[1]))
            
                    dst_profile = cog_profiles.get("deflate")
                    cog_translate(
                        mem,
                        OUTFILE,
                        dst_profile,
                        in_memory=False
                    )
            
            print("GeoTIFF has been created successfully with GDAL.")

/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_11_MON_L2A.tif
counts [[32. 39. 46. ... 17. 24. 31.]
 [40. 49. 60. ... 29. 26. 27.]
 [38. 43. 55. ... 43. 35. 11.]
 ...
 [54. 60. 50. ... 47. 56. 61.]
 [34. 33. 50. ... 43. 44. 34.]
 [21. 19. 14. ... 28. 41. 53.]]
zi [[141.30999947 165.37000012 182.34999943 ...  62.91000056  63.18000054
   79.96000028]
 [157.05000043 207.07999945 244.24000072 ... 139.62999892  86.40999985
   69.55000019]
 [181.60000062 228.29000092 244.06000209 ... 148.74999881  92.5200007
   27.76000023]
 ...
 [143.06999946 157.48000002 131.41000128 ... 146.34000015 178.20999956
  184.88000083]
 [ 88.35000014  87.2699995  135.72000074 ... 141.1099999  156.53000093
   94.46000028]
 [ 53.61000061  49.03999996  36.98999977 ... 349.80999708 196.11999941
  168.46999955]]
94.0373541424532
50.610949537773


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/6b76c429-7d48-48ee-ab54-fc4469762fec/6b76c429-7d48-48ee-ab54-fc4469762fec.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_11_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_12_MON_L2A.tif
counts [[35. 32. 18. ... 12. 15. 20.]
 [13. 15. 19. ... 17. 18. 24.]
 [20. 20. 19. ... 24. 17.  9.]
 ...
 [ 6. 13. 23. ... 11. 25. 32.]
 [16. 24. 10. ... 17. 12. 22.]
 [25. 19. 24. ... 18. 13.  3.]]
zi [[ 90.73999929  92.22999978  49.89000058 ...  29.25000024  37.71000004
   49.55000043]
 [ 37.94999981  40.3099997   52.21000028 ...  41.62999964  43.58000016
   58.98000026]
 [ 62.17999983  52.63999939  50.01999974 ...  60.11000013  41.38999987
   22.33000016]
 ...
 [ 33.47000051  46.25000048  68.77000046 ...  56.97000027 187.06999946
  264.42000246]
 [ 83.02999949  86.8499999   31.37999988 ... 129.52999949  61.42999911
   83.32000017]
 [110.07000017  96.82999969  90.06000066 ...  66.73999977  70.60999966
   20.53000021]]
92.0373547148086
49.6109499457992


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/395aad75-979e-4d72-a03c-e5463f365e5b/395aad75-979e-4d72-a03c-e5463f365e5b.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_12_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_13_MON_L2A.tif
counts [[12. 15. 11. ... 22. 40. 34.]
 [13.  8. 11. ... 38. 28. 15.]
 [ 6. 14. 17. ... 22. 30. 39.]
 ...
 [ 0.  0.  9. ... 38. 48. 60.]
 [ 0.  0. 27. ... 41. 43. 37.]
 [ 0.  0.  8. ... 31. 28. 17.]]
zi [[ 72.53000021  81.20000076  77.36000061 ... 112.80999947 178.48000026
  196.27000022]
 [103.90000129  74.97000122  67.3499999  ... 162.11999941 133.28000069
   77.1400001 ]
 [ 38.94000101 128.95000172 130.21999979 ...  95.82000089 129.42000055
  187.42000103]
 ...
 [  0.           0.          25.13999987 ...  98.62999964 124.94000006
  158.13999963]
 [  0.           0.          71.87000036 ... 108.40999842 109.02999949
   95.25999975]
 [  0.           0.          23.69999981 ...  81.75000048  73.17000055
   43.31000042]]
93.037354326909
50.6109499643647


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/488b4439-533d-484e-a282-3505c763d4d3/488b4439-533d-484e-a282-3505c763d4d3.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_13_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_14_MON_L2A.tif
counts [[16. 21. 22. ... 24. 23. 28.]
 [25. 20. 21. ... 34. 21. 14.]
 [38. 29. 21. ... 21. 22. 24.]
 ...
 [69. 77. 68. ... 19. 28. 17.]
 [44. 62. 53. ... 17. 17. 17.]
 [56. 23. 47. ... 13. 16. 21.]]
zi [[105.37000036  94.13000083 103.76999998 ...  68.84000015  93.38000011
   97.39000082]
 [131.32999873  83.2900002   89.42999959 ...  97.99000001  58.2699995
   45.28000021]
 [142.01000047 122.60000086 100.51000023 ...  61.37999988  70.91999984
   68.73000002]
 ...
 [246.16000032 313.00999928 334.23000026 ...  87.78999972 143.02999997
   86.45000124]
 [145.84999919 245.14000058 220.61999965 ...  62.46000004 102.10999966
  106.63999987]
 [225.87999916 107.29000092 300.63999939 ...  43.36999989  86.63000011
   91.81999993]]
91.0373562296455
49.610949854879


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/ffc293b9-cb3a-417a-9e2f-e71d3ab47504/ffc293b9-cb3a-417a-9e2f-e71d3ab47504.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_14_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_15_MON_L2A.tif
counts [[17. 20. 23. ... 15. 13. 14.]
 [18. 23. 44. ... 10. 12. 19.]
 [49. 42. 30. ... 21. 13. 12.]
 ...
 [53. 48. 59. ...  0.  0.  0.]
 [56. 80. 68. ...  0.  0.  0.]
 [77. 68. 53. ...  0.  0.  0.]]
zi [[126.97999883 106.98999953  85.87999988 ...  80.69999981  94.47000051
  102.05999899]
 [ 74.55000019  89.97000074 210.54999948 ...  53.52000022  92.20000052
  199.12000084]
 [157.27000022 157.12999964  83.41000009 ... 155.67999959  72.01000071
   55.09999919]
 ...
 [165.29000044 133.89999962 162.34999919 ...   0.           0.
    0.        ]
 [168.30000043 223.53999972 171.78000045 ...   0.           0.
    0.        ]
 [247.47999954 195.38999963 135.55000091 ...   0.           0.
    0.        ]]
92.0373540795052
50.6109486977635


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/8f2e196c-42ae-49a9-900a-550e288a41ce/8f2e196c-42ae-49a9-900a-550e288a41ce.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_15_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_16_MON_L2A.tif
counts [[70. 72. 63. ... 27. 22. 19.]
 [81. 79. 75. ... 38. 34. 25.]
 [44. 63. 53. ... 46. 39. 43.]
 ...
 [ 2. 10. 17. ... 59. 50. 48.]
 [ 7.  6. 24. ... 54. 63. 61.]
 [ 8.  7. 22. ... 72. 67. 62.]]
zi [[273.03000212 293.70999813 380.17000008 ... 152.71000004 159.78000093
  142.28000188]
 [527.799999   296.26000047 338.87000132 ... 207.29000139 181.299999
  112.67999959]
 [195.32000089 216.0400002  169.57999969 ... 264.0899992  179.89999986
  179.33999944]
 ...
 [ 18.23999977  94.73000145 153.9799993  ... 175.61000061 181.25000024
  158.32999969]
 [ 61.98000002  68.04999924 291.60000134 ... 181.75000024 225.60999918
  174.75000024]
 [ 72.08999968 116.79999924 234.40000057 ... 205.5100019  212.1699996
  176.27999949]]
91.0373570906393
50.6109497731506


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/09c4ebe1-a89c-45d7-81c3-4c34765a789e/09c4ebe1-a89c-45d7-81c3-4c34765a789e.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_16_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_17_MON_L2A.tif
counts [[32. 13. 12. ... 23. 25. 27.]
 [ 6.  7. 14. ...  1.  3.  4.]
 [16. 11. 19. ...  3.  5.  7.]
 ...
 [50. 59. 79. ... 11.  9.  9.]
 [30. 12.  2. ... 10. 11.  9.]
 [ 0.  6.  7. ...  1.  0.  0.]]
zi [[ 232.41000056   69.36000013   50.82000041 ...  189.31999826
   142.33000064   73.50000024]
 [  39.70000005   41.90999961   51.9400003  ...   15.55000019
    32.06999898   20.68999982]
 [  78.80000091   53.95000005   84.90000129 ...   44.68000031
    52.46999979   29.03999972]
 ...
 [1327.40000534 1601.06000662 1917.92000389 ...  203.33999872
   206.57999992  197.14999962]
 [ 834.90999413  304.27999878   63.91999817 ...  246.14999771
   236.65999794  194.74000168]
 [   0.          136.34999847  164.95000076 ...   26.47999954
     0.            0.        ]]
108.037355776952
49.6109494515788


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/51f428bf-1822-474e-8aa1-ea80380b7d5a/51f428bf-1822-474e-8aa1-ea80380b7d5a.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_17_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_18_MON_L2A.tif
counts [[32. 33. 34. ...  8. 10. 13.]
 [33. 46. 42. ...  1.  1.  1.]
 [20. 19. 34. ...  0.  2. 16.]
 ...
 [ 8. 12. 12. ... 84. 99. 93.]
 [10. 21. 16. ...  9. 14. 13.]
 [21. 13. 13. ...  0.  1.  0.]]
zi [[ 210.47000194  244.11000299  179.37999964 ...   45.96000051
   208.40999842  109.20999908]
 [ 130.82000065  230.75999928  219.92999959 ...   20.12999916
    15.31999969   16.21999931]
 [  88.43999982   88.95000029  159.59000111 ...    0.
    36.45999908  149.82999992]
 ...
 [  40.75         89.20999837  105.38999939 ... 2060.22000217
  2492.33998299 2187.16000414]
 [ 119.14999938  146.49000192  152.08999968 ...  318.68000221
   355.49999428  356.30999756]
 [ 150.14000034   84.22999907   80.86000061 ...    0.
    22.45000076    0.        ]]
107.037357108785
49.6109444087761


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/802cbc21-604b-42dd-bad0-7dbece5a2aa5/802cbc21-604b-42dd-bad0-7dbece5a2aa5.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_18_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_19_MON_L2A.tif
counts [[ 5. 11. 21. ... 33. 35. 44.]
 [21. 12. 15. ... 34. 40. 20.]
 [35. 33. 27. ... 24. 21. 21.]
 ...
 [44. 39. 19. ...  5.  0.  0.]
 [56. 21. 31. ...  7.  7. 13.]
 [42. 72. 54. ... 17. 20. 25.]]
zi [[ 13.11999989  35.57000017  57.01999998 ... 192.85000086 188.87000108
  205.200001  ]
 [ 61.24000025  33.8499999   43.51000047 ... 158.96000028 190.85999966
   86.49000049]
 [130.21000004 108.06000018  87.48000073 ...  95.36000037 114.24999952
  112.90999937]
 ...
 [123.48999953 101.64999938  45.19999957 ...  47.05999947   0.
    0.        ]
 [174.58999944  60.          85.96000051 ...  37.02999997  48.10000062
   79.43000031]
 [121.14999986 194.96999979 144.27000022 ... 187.36999989 186.71999836
  215.1600008 ]]
106.037354998044
49.6109496203229


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/51393581-6bea-43a9-a14c-6952e5d38b50/51393581-6bea-43a9-a14c-6952e5d38b50.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_19_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_1_MON_L2A.tif
counts [[15. 12. 10. ...  4.  6.  3.]
 [12. 14. 23. ...  1.  4.  1.]
 [17. 12. 11. ...  4.  0.  0.]
 ...
 [28. 34. 51. ... 23. 17. 12.]
 [ 6. 15. 24. ... 17. 14. 20.]
 [ 2.  9. 17. ... 10. 12. 12.]]
zi [[102.43000078  71.48000002  79.91999912 ... 115.28999901 303.1400013
  123.11000252]
 [131.77000165 195.63000059 248.04000092 ...  19.5         79.54999924
   20.31999969]
 [112.84000039 148.59000134 137.69000149 ...  79.30999851   0.
    0.        ]
 ...
 [161.85999846 214.96999788 172.93999839 ... 518.4100008  405.09000111
  298.54000092]
 [ 26.05999994  94.01999974 133.13999987 ... 368.61999798 311.00000191
  446.58999729]
 [  8.37000012  27.74000001  51.72999978 ... 170.72000265 296.5899992
  219.69999886]]
107.037355060962
50.6109488512985


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/b303af54-506d-463b-bc68-3b283b0929d0/b303af54-506d-463b-bc68-3b283b0929d0.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_1_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_2_MON_L2A.tif
counts [[46. 56. 35. ... 44. 26. 16.]
 [37. 28. 40. ... 16. 17. 32.]
 [52. 41. 37. ... 38. 32. 34.]
 ...
 [37. 20. 40. ... 19. 31. 59.]
 [28. 39. 45. ... 47. 64. 60.]
 [41. 37. 44. ... 52. 56. 59.]]
zi [[124.84000063 152.6900003   99.03999972 ... 128.06000018  75.97999978
   44.22999954]
 [111.28000021  74.80000019 107.83999991 ...  44.43000007  46.91999984
   89.6400001 ]
 [139.52000117 118.53999996 116.06999993 ... 104.12999988  90.14999962
   95.45999956]
 ...
 [ 94.25000048  50.57999992 117.68000007 ... 206.78999901 316.22999835
  713.22000217]
 [ 77.18999982 100.31000018 123.35000014 ... 382.34000206 674.17000246
  733.0200007 ]
 [111.40999985  98.95000052 120.3300004  ... 580.73000169 509.70000052
  500.70999908]]
95.0373540932508
49.6109497403471


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/9c65ade6-0edb-40b8-be29-bac956d66cf1/9c65ade6-0edb-40b8-be29-bac956d66cf1.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_2_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_3_MON_L2A.tif


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/56388d5c-f607-49ec-a809-0f0d16d1b036/56388d5c-f607-49ec-a809-0f0d16d1b036.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_3_MON_L2A.tif


counts [[31. 23. 19. ... 56. 33. 46.]
 [44. 46. 39. ... 49. 52. 39.]
 [37. 30. 43. ... 50. 43. 59.]
 ...
 [57. 60. 54. ... 33. 36. 47.]
 [57. 52. 58. ... 46. 44. 13.]
 [60. 41. 19. ... 37. 25. 46.]]
zi [[ 77.40999961  59.65999985  49.         ... 166.87999964  86.79999995
  135.25      ]
 [110.70000029 116.44999933  98.31000066 ... 133.96999931 146.3900001
  108.48000026]
 [ 95.34999967  78.55000067 107.80000043 ... 133.15999985 116.91000104
  155.84999967]
 ...
 [251.41999984 228.77000046 186.84999919 ... 383.32999825 343.09999967
  134.45000029]
 [221.9399991  182.80999947 228.84999943 ... 264.24000025 136.9699986
   34.79000044]
 [207.68000007 153.27999878  62.97000003 ... 230.25000072  70.80999923
  126.53999972]]
94.0373562867492
49.6109497996439
GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_4_MON_L2A.tif
counts [[41. 34. 21. ... 44. 43. 33.]
 [17. 16. 20. ... 12. 22. 41.]
 [16. 26. 25. ... 24. 31. 28.]
 ...
 [58. 

/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/02a39cc9-35d3-4ce4-a4e9-21d03e55665b/02a39cc9-35d3-4ce4-a4e9-21d03e55665b.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_4_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_5_MON_L2A.tif
counts [[27. 37. 32. ... 22. 14. 11.]
 [29. 37. 26. ... 22. 28. 23.]
 [49. 23. 32. ... 12. 15. 26.]
 ...
 [10.  7.  8. ... 34. 50. 52.]
 [14. 18. 12. ... 44. 49. 61.]
 [ 9. 16. 11. ... 41. 38. 28.]]
zi [[ 89.91000009 142.16000009 132.26000142 ...  94.3799994   44.21000051
   35.22000003]
 [109.73000097 141.44999909  74.49000001 ... 103.95000052 112.77000117
   79.21000028]
 [165.57000017  84.05000067 103.23000002 ...  77.86999965 104.25000072
  119.01000047]
 ...
 [ 87.57000113  66.25        72.61000109 ... 110.94999957 138.83999991
  164.66000056]
 [279.64000225 359.24999905 275.28999901 ... 130.05000091 140.15999937
  169.19999909]
 [ 53.33000064 259.27000046 219.71999907 ... 118.31999969 111.88000083
   84.34000015]]
105.037354891895
49.6109496421254


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/fdde7b54-fe53-4480-934c-fac3017656b0/fdde7b54-fe53-4480-934c-fac3017656b0.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_5_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_6_MON_L2A.tif


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/6c2969b1-a87f-467e-af4e-16ecc8dfb39f/6c2969b1-a87f-467e-af4e-16ecc8dfb39f.tif' mode='w+'>

Updating dataset tags...


counts [[36. 45. 54. ...  6.  5. 11.]
 [36. 33. 24. ...  7.  6. 10.]
 [41. 41. 54. ... 13. 13. 13.]
 ...
 [22. 22. 22. ... 32. 38. 30.]
 [23. 20. 21. ... 31. 22. 12.]
 [38. 30. 35. ... 17.  9.  4.]]
zi [[ 93.63000011 122.28999972 143.25999951 ...  26.00999999  64.22000027
   97.43000054]
 [104.92000031  99.02999973  73.2900002  ...  95.53999901  48.51999974
   28.57000017]
 [124.28000021 118.72000027 151.31000018 ...  45.77000022 175.56999969
   93.51999879]
 ...
 [ 60.35999966  60.42999983  69.15000033 ... 132.6900022  243.42000103
  190.54999971]
 [ 65.75999975  57.73000002  65.94999981 ... 192.48000026  77.08999991
   82.74999952]
 [110.08999991 100.90999961 116.32999945 ...  59.57999945  35.90000033
   21.6099999 ]]
106.037354054051
50.6109490301227


Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_6_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_7_MON_L2A.tif
counts [[22. 25. 20. ... 32. 21. 28.]
 [27. 29. 26. ... 31. 30. 35.]
 [18. 28. 24. ... 28. 36. 43.]
 ...
 [27. 40. 40. ... 21. 21. 11.]
 [32. 29. 23. ... 10.  5. 12.]
 [18. 12. 21. ...  9. 10.  8.]]
zi [[ 93.70999908  85.79999971  73.10000062 ... 129.08000159  69.0599997
   77.11999965]
 [ 87.39000034  84.43999982  96.90999985 ... 105.42999983 110.96000028
  167.36000013]
 [ 55.72000003  95.00999975  77.11999989 ...  97.69999957 123.07000041
  135.02000022]
 ...
 [159.93000054 145.99999833 328.25       ... 409.65999985 459.86000061
  265.88999891]
 [246.36999917  83.53999949  74.6699996  ... 159.46000099 130.9299984
  229.08999968]
 [ 94.40999961  39.4599998  126.8500011  ... 128.12999916  96.40000105
   75.9599998 ]]
104.03735530995
49.6109499225931


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/8398f114-4ef8-4a26-96de-f1beb0329538/8398f114-4ef8-4a26-96de-f1beb0329538.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_7_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_8_MON_L2A.tif
counts [[10.  7. 11. ... 36. 34. 24.]
 [ 2.  5.  7. ... 28. 34. 35.]
 [ 0.  2. 10. ... 18. 24. 39.]
 ...
 [38. 28. 31. ... 21. 21. 23.]
 [45. 29. 31. ... 26. 26. 21.]
 [28. 35. 34. ... 33. 26. 35.]]
zi [[186.41000271 152.849998    89.11999774 ... 102.58999991  96.24000049
   64.34000015]
 [ 39.95000076 109.04999924  70.43999958 ...  97.77000117 123.70999956
  113.06999922]
 [  0.          40.60000038 103.00000095 ...  49.58999991  62.97000003
  126.00999975]
 ...
 [280.34000111 191.3700006  131.41999865 ...  59.75        56.13999915
   65.82000041]
 [157.5600009  134.75999904 133.42000079 ...  74.13000035  73.64000082
   60.47999954]
 [101.45000076  90.00000024 117.20999885 ...  95.58000064  80.04000044
   98.96000028]]
105.037354009046
50.610949254119


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/0c38347c-8e1d-40fb-ada5-73df9be04d0c/0c38347c-8e1d-40fb-ada5-73df9be04d0c.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_8_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.
/projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_9_MON_L2A.tif
counts [[17. 28. 24. ...  6.  7.  7.]
 [27. 35. 28. ...  3.  1.  0.]
 [20. 28. 30. ...  8.  8.  6.]
 ...
 [21. 21. 15. ... 41. 35. 44.]
 [21. 20. 23. ... 40. 53. 43.]
 [28. 22. 22. ... 36. 38. 35.]]
zi [[105.10000157  82.07999945 116.25999928 ... 116.66000175 142.31000137
  119.82999849]
 [319.56000066 118.86999965 238.20999908 ...  28.54999971  18.38999939
    0.        ]
 [153.44000053 110.80999947 143.43000078 ...  83.97999954  83.6500001
   58.70000076]
 ...
 [387.34999943 373.74999809 301.09999943 ... 360.6400001  179.41000009
  222.46999979]
 [413.16999912 225.30000019 382.80999851 ... 150.59000039 222.46000051
  181.47000074]
 [734.26999617 581.91999722 518.53000355 ... 109.42000031 120.28999996
   97.06999969]]
104.037355976334
50.6109486401701


/tmp/ipykernel_2631/335921371.py:83: RasterioDeprecationWarning: Source dataset should be opened in read-only mode. Use of datasets opened in modes other than 'r' will be disallowed in a future version.
  cog_translate(
Reading input: <open DatasetWriter name='/vsimem/e6f4c656-0fa7-4c54-813b-e4764a710281/e6f4c656-0fa7-4c54-813b-e4764a710281.tif' mode='w+'>

Updating dataset tags...
Writing output to: /projects/my-public-bucket/Data/NASA_CMS_2023/MONGOLIA/GRID/fid_9_MON_L2A.tif


GeoTIFF has been created successfully with GDAL.


In [23]:
# open raster and choose band to find min, max
raster = '/projects/output_gdal_200_8.tif'
#gtif = gdal.Open(raster)
#srcband = gtif.GetRasterBand(1)

with rasterio.open(raster) as dataset:
    data = dataset.read()

    if dataset.nodata is not None:
        data = np.ma.masked_equal(data, dataset.nodata)

    # Compute statistics
    min_value = np.min(data)
    max_value = np.max(data)
    mean_value = np.mean(data)
    std_dev = np.std(data)

    # Print the statistics
    print(f"Min: {min_value}")
    print(f"Max: {max_value}")
    print(f"Mean: {mean_value}")
    print(f"Standard Deviation: {std_dev}")

Min: 0
Max: 80
Mean: 13.53555
Standard Deviation: 8.726241241078544
